### ISSUE TITLE
mining rewards not visible in simplewallet.

### ISSUE THREAD

**Issue by n4kashu** [zano-project/zano#1]
mining reward are not visible in wallet. rescanned, restored.. resynced whole daemon... no help. any avice?

**Comment by cryptozoidberg** [comment]
Hi, if you "rescanned, restored.. resynced whole daemon", from my expirience that could means that money have not been transfered yet, or it have been transfered to some other address. 
Anyway, clould you provide id of transactions with payouts, if you have it, and what pool do you use?

**Comment by n4kashu** [comment]
Hi I was solo mining..

part of daemon log:

2019-Jan-17 19:33:43.230860 [miner 28]Found block for difficulty: 603412
2019-Jan-17 19:33:43.230960 [miner 28]MINING PAUSED
2019-Jan-17 19:33:43.249859 [miner 28]Added tx to blockchain: <7cea87ef49a706d0f7242d4b3d72064eacf5ae798b06ca4419103c235e58d546> via block at 3947 id <6d47f..>, ins: 1, outs: 1, outs sum: 0.001 (fee: 0[coinbase])
2019-Jan-17 19:33:43.251631 [miner 28]Mining tx verification ok, blocks_size_median = 0
2019-Jan-17 19:33:43.251786 [miner 28]+++++ BLOCK SUCCESSFULLY ADDED [PoW] Sq: 0
id:     <6d47feae6e742ebf6afd59b88b649d5da5817ef61398d393e5ea2a5d344b0314>, block ts: 1547750019 (diff: -4s)
PoW:    <0000012e87884991b12f2374ab7beb79b80a11c0924bdc3cd09c03ad64880f33>
HEIGHT 3947, difficulty: 603412, cumul_diff_precise: 1220496375, cumul_diff_adj: 550514373 (+603412)
block reward: 0.001 (0.001 + 0.0), coinbase_blob_size: 103, cumulative size: 0, tx_count: 0, 21(20681/16883/1370/41/155/1823)micrs
hr: 4359
2019-Jan-17 19:33:43.714388 [miner 28][POST RELAY] N8currency16NOTIFY_NEW_BLOCKE relayed contexts list:
207.154.255.10:11196 OUT
207.154.228.141:11196 OUT
144.76.183.143:11196 OUT
207.154.237.82:11196 OUT
207.154.240.198:11196 OUT

2019-Jan-17 19:33:43.714472 [miner 28]handle_block_found timings (ms): total: 484, add new block: 29, update template: 454, pack txs: 0, relay: 1
2019-Jan-17 19:33:43.714494 [miner 28]MINING RESUMED
hr: 3572
2019-Jan-17 19:33:49.449313 [P2P5][207.154.228.141:11196 OUT][HANDLE]NOTIFY_NEW_BLOCK <b4d3fa9f3af61ca419b717f8e9186bbec13b4ba7be3515209edc2a2158bb3256> HEIGHT 3948 (hop 1)
2019-Jan-17 19:33:49.450804 [P2P1][207.154.240.198:11196 OUT][HANDLE]NOTIFY_NEW_BLOCK <b4d3fa9f3af61ca419b717f8e9186bbec13b4ba7be3515209edc2a2158bb3256> HEIGHT 3948 (hop 1)

are there pools available? cant find this info..:)

**Comment by n4kashu** [comment]
getting good blocks but nothing in wallet which is weird..

**Comment by cryptozoidberg** [comment]
Oh, i see, can you send me:
* wallet file which correspond to a address that you pass to mining
*  exact command that you gave to miner for start mining? (via command line or via daemon console)
PS: thanks for joining our testnet, despite we haven't announced it yet :)

**Comment by n4kashu** [comment]
heh, found compilable code so why not give it a shot..:)

I have started both ways, from wallet: start_mining
 for address ZxDWk8F5PWvCASARMRhBmNgGCzdDstg12F5n98A2v85LejBienJ1KNm2qkLy77reFxQk8XoNZzAGUKd4B3rX6Qq61M9HCBhoE
and from daemon after restarts and deleting stuff..:
start_mining ZxCjWXkE864Hcwwdoy8tYMdZrvvdhYZKZK7gKgaZUDr13E5pRVZbK4B7x1H1wJA8NmWtcj9nnZ6MRMRaai9AnYJj3Ad1c5tnx 40
specifying number of ports..

I did not see any exceptions in simplewallet.log whatsoever..

**Comment by cryptozoidberg** [comment]
40 threads ... wow... impressive number. 
Thanks for report, we'll work on this and i'll get back as soon as we find out what's is wrong with that.

**Comment by n4kashu** [comment]
rebuildding the code and restoring wallet worked. all rewards visible now. you can close this ticket. thank you for fast reaction and support.will  report any irregularities. cheers!

**Comment by cryptozoidberg** [comment]
it probably happend if the wallet(or part of it's libs) was build for previous testnet and daemon for current, that could explain this bug, but anyway, glad that i self-solved.

**Comment by auroracoin** [comment]
No announcement of mining ... unfair.

**Comment by Scryptee** [comment]
@auroracoin it's testnet.

**Comment by auroracoin** [comment]
My apologies. :)
